# Generated by Django 2.0.6 on 2018-09-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_mongo', models.CharField(max_length=1000, null=True)),
                ('image1', models.CharField(max_length=10000, null=True)),
                ('image2', models.CharField(max_length=10000, null=True)),
                ('image3', models.CharField(max_length=10000, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
