# Generated by Django 2.0.6 on 2018-10-18 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_mongo', models.CharField(max_length=10000, null=True)),
                ('id_creador', models.CharField(max_length=10000, null=True)),
                ('image1', models.CharField(max_length=10000000, null=True)),
                ('date_image1', models.DateTimeField(null=True)),
                ('image2', models.CharField(max_length=10000000, null=True)),
                ('date_image2', models.DateTimeField(null=True)),
                ('image3', models.CharField(max_length=10000000, null=True)),
                ('date_image3', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_mongo', models.CharField(max_length=10000, null=True)),
                ('id_creador', models.CharField(max_length=10000, null=True)),
                ('image1', models.CharField(max_length=10000000, null=True)),
                ('date_image1', models.DateTimeField(null=True)),
                ('image2', models.CharField(max_length=10000000, null=True)),
                ('date_image2', models.DateTimeField(null=True)),
                ('image3', models.CharField(max_length=10000000, null=True)),
                ('date_image3', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='face.Person'),
        ),
    ]
